show_analysis_paths: False
show_analysis_time: False

no_ai: True

read_count_multiplier: 0.001
read_count_prefix: "K"
read_count_desc: "thousands"

# Sample grouping
table_sample_merge:
  "(R1)": "_1"
  "(R2)": "_2"

run_modules:
  - fastqc
  - fastp
  - metaphlan
  - custom_content

module_order:
  - fastqc:
      name: "FastQC (raw)"
  - fastp:
      name: "FastP (Read preprocessing)"
  - metaphlan:
      name: "Metaphlan"

report_section_order:
  software_versions:
    order: -1000

table_columns_visible:
  "FastP (Read preprocessing)":
    after_filtering_gc_content: false
    pct_duplication: false

extra_fn_clean_exts:
  - "_profile"
  - type: remove
    pattern: "_1"
    module: fastp


disable_version_detection: true
skip_versions_section: true